alerting:
  alertmanagers:
  - static_configs:
    - targets: null
global:
  evaluation_interval: 15s
  scrape_interval: 15s
rule_files: null
scrape_configs:
- job_name: libvirt
  static_configs:
  - targets:
    - 10.10.1.1:3002
    - 10.10.1.2:3002
    - 10.10.1.3:3002
- job_name: cube
  static_configs:
  - targets:
    - 10.10.1.1:3003
    - 10.10.1.2:3003
    - 10.10.1.3:3003
- job_name: scvm
  static_configs:
  - targets:
    - 10.10.1.11:3003
    - 10.10.1.12:3003
    - 10.10.1.13:3003
- job_name: ccvm
  static_configs:
  - targets:
    - 10.10.1.10:3003
- job_name: cube-process-exporter
  metric_relabel_configs:
  - regex: (.*);(.*);(.*);(.*);(.*)
    replacement: $1
    source_labels:
    - groupname
    target_label: comm
  - regex: (.*);(.*);(.*);(.*);(.*)
    replacement: $2
    source_labels:
    - groupname
    target_label: exebase
  - regex: (.*);(.*);(.*);(.*);(.*)
    replacement: $3
    source_labels:
    - groupname
    target_label: exefull
  - regex: (.*);(.*);(.*);(.*);(.*)
    replacement: $4
    source_labels:
    - groupname
    target_label: username
  - regex: (.*);(.*);(.*);(.*);(.*)
    replacement: $5
    source_labels:
    - groupname
    target_label: matches
  static_configs:
  - targets:
    - 10.10.1.1:3004
    - 10.10.1.2:3004
    - 10.10.1.3:3004
- job_name: scvm-process-exporter
  metric_relabel_configs:
  - regex: (.*);(.*);(.*);(.*);(.*)
    replacement: $1
    source_labels:
    - groupname
    target_label: comm
  - regex: (.*);(.*);(.*);(.*);(.*)
    replacement: $2
    source_labels:
    - groupname
    target_label: exebase
  - regex: (.*);(.*);(.*);(.*);(.*)
    replacement: $3
    source_labels:
    - groupname
    target_label: exefull
  - regex: (.*);(.*);(.*);(.*);(.*)
    replacement: $4
    source_labels:
    - groupname
    target_label: username
  - regex: (.*);(.*);(.*);(.*);(.*)
    replacement: $5
    source_labels:
    - groupname
    target_label: matches
  static_configs:
  - targets:
    - 10.10.1.11:3004
    - 10.10.1.12:3004
    - 10.10.1.13:3004
- job_name: ccvm-process-exporter
  metric_relabel_configs:
  - regex: (.*);(.*);(.*);(.*);(.*)
    replacement: $1
    source_labels:
    - groupname
    target_label: comm
  - regex: (.*);(.*);(.*);(.*);(.*)
    replacement: $2
    source_labels:
    - groupname
    target_label: exebase
  - regex: (.*);(.*);(.*);(.*);(.*)
    replacement: $3
    source_labels:
    - groupname
    target_label: exefull
  - regex: (.*);(.*);(.*);(.*);(.*)
    replacement: $4
    source_labels:
    - groupname
    target_label: username
  - regex: (.*);(.*);(.*);(.*);(.*)
    replacement: $5
    source_labels:
    - groupname
    target_label: matches
  static_configs:
  - targets:
    - 10.10.1.10:3004
- job_name: cube-blackbox
  metrics_path: /probe
  params:
    conut:
    - 3
    module:
    - icmp
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: pingip
  - replacement: 10.10.1.10:3005
    target_label: __address__
  static_configs:
  - targets:
    - 10.10.1.1
    - 10.10.1.2
    - 10.10.1.3
- job_name: scvm-blackbox
  metrics_path: /probe
  params:
    conut:
    - 3
    module:
    - icmp
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: pingip
  - replacement: 10.10.1.10:3005
    target_label: __address__
  static_configs:
  - targets:
    - 10.10.1.11
    - 10.10.1.12
    - 10.10.1.13
- job_name: ccvm-blackbox
  metrics_path: /probe
  params:
    conut:
    - 3
    module:
    - icmp
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: pingip
  - replacement: 10.10.1.10:3005
    target_label: __address__
  static_configs:
  - targets:
    - 10.10.1.10
- job_name: blackbox-tcp
  metrics_path: /probe
  params:
    module:
    - tcp_connect
  relabel_configs:
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: pingip
  - replacement: 10.10.1.10:3005
    target_label: __address__
  static_configs:
  - targets:
    - 10.10.1.1:9090
    - 10.10.1.2:9090
    - 10.10.1.3:9090
    - 10.10.1.10:8080
    - 10.10.1.10:3306
    - 10.10.1.1:3002
    - 10.10.1.2:3002
    - 10.10.1.3:3002
    - 10.10.1.1:3003
    - 10.10.1.2:3003
    - 10.10.1.3:3003
    - 10.10.1.11:3003
    - 10.10.1.12:3003
    - 10.10.1.13:3003
    - 10.10.1.10:3003
    - 10.10.1.1:3004
    - 10.10.1.2:3004
    - 10.10.1.3:3004
    - 10.10.1.11:3004
    - 10.10.1.12:3004
    - 10.10.1.13:3004
    - 10.10.1.10:3004
    - 10.10.1.10:3005
